export const SENTENCES = [
  // General / Concepts
  "Clean code always looks like it was written by someone who cares.",
  "Premature optimization is the root of all evil in programming.",
  "Recursion is a method where the solution depends on solutions to smaller instances of the same problem.",
  "A closure is the combination of a function bundled together with references to its surrounding state.",
  "Big O notation is used to classify algorithms according to how their run time or space requirements grow.",
  "The single responsibility principle states that every module or class should have responsibility over a single part of the functionality.",
  "Dependency injection is a technique whereby one object supplies the dependencies of another object.",
  "Polymorphism allows objects of different types to be accessed through the same interface.",
  "Encapsulation is the bundling of data with the methods that operate on that data.",
  "An abstract class is a class that cannot be instantiated and is designed to be subclassed.",
  "Composition over inheritance is the principle that classes should achieve polymorphic behavior through composition.",
  "Memoization is an optimization technique used to speed up programs by storing the results of expensive function calls.",
  "Immutability means that once an object is created, its state cannot be modified.",
  "Pure functions always produce the same output for the same input and have no side effects.",
  "The open-closed principle states that software entities should be open for extension but closed for modification.",

  // Frontend
  "React components implement a render method that takes input data and returns what to display.",
  "CSS Grid Layout excels at dividing a page into major regions or defining the relationship in terms of size, position, and layer.",
  "The Document Object Model is a cross-platform and language-independent interface that treats an XML or HTML document as a tree structure.",
  "Event bubbling describes how the browser handles events targeted at nested elements.",
  "TypeScript adds static typing to JavaScript to enable better tooling and catch errors early.",
  "Virtual DOM is a programming concept where an ideal representation of a UI is kept in memory and synced with the real DOM.",
  "Flexbox is a one-dimensional layout method for arranging items in rows or columns.",
  "Shadow DOM provides encapsulation for the JavaScript, CSS, and templating in a Web Component.",
  "Server-side rendering generates the full HTML for a page on the server in response to navigation.",
  "Web Components are a suite of different technologies allowing you to create reusable custom elements.",
  "The useState hook lets you add React state to function components.",
  "useEffect performs side effects in function components and serves the same purpose as lifecycle methods.",
  "Context provides a way to pass data through the component tree without having to pass props down manually at every level.",
  "Redux is a predictable state container for JavaScript apps that helps you write applications that behave consistently.",
  "Webpack is a static module bundler for modern JavaScript applications.",
  "Babel is a JavaScript compiler that converts ECMAScript 2015+ code into backwards compatible versions.",
  "Progressive web apps are web applications that load like regular web pages but offer functionality such as working offline.",
  "Responsive design ensures that web pages render well on a variety of devices and window sizes.",
  "The box model describes the rectangular boxes generated for elements in the document tree.",
  "CSS preprocessors like Sass extend CSS with variables, nested rules, and mixins.",

  // Backend / Database
  "RESTful APIs use standard HTTP methods like GET, POST, PUT, and DELETE to perform operations on resources.",
  "SQL injection is a code injection technique that might destroy your database.",
  "Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity.",
  "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
  "ACID properties ensure that database transactions are processed reliably.",
  "Middleware functions have access to the request object, response object, and the next middleware function in the cycle.",
  "GraphQL is a query language for APIs that provides a complete description of the data in your API.",
  "MongoDB is a document-oriented NoSQL database used for high volume data storage.",
  "An ORM is a technique that lets you query and manipulate data from a database using an object-oriented paradigm.",
  "JWT tokens contain three parts separated by dots: header, payload, and signature.",
  "Microservices architecture structures an application as a collection of loosely coupled services.",
  "Load balancing distributes network traffic across multiple servers to ensure no single server bears too much demand.",
  "Caching stores copies of files in a temporary storage location so future requests can be served faster.",
  "WebSockets provide full-duplex communication channels over a single TCP connection.",
  "Authentication verifies who a user is, while authorization determines what resources a user can access.",
  "Rate limiting controls the amount of incoming and outgoing traffic to or from a network.",
  "Message queues provide asynchronous communication between different parts of a system.",
  "Sharding is a database architecture pattern related to horizontal partitioning of data across multiple databases.",
  "Database indexing creates a data structure that improves the speed of data retrieval operations.",
  "Foreign keys establish a link between data in two tables by referencing the primary key of another table.",

  // DevOps / Tools
  "Git is a distributed version control system for tracking changes in source code during software development.",
  "Docker containers wrap up a piece of software in a complete filesystem that contains everything it needs to run.",
  "Continuous Integration is the practice of merging all developers' working copies to a shared mainline several times a day.",
  "Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.",
  "CI/CD pipelines automate the steps in your software delivery process such as builds, tests, and deployments.",
  "Infrastructure as code manages and provisions computing infrastructure through machine-readable definition files.",
  "Blue-green deployment is a technique that reduces downtime by running two identical production environments.",
  "Feature flags allow you to turn features on and off without deploying new code.",
  "Log aggregation collects log data from multiple sources into a centralized location for analysis.",
  "Monitoring observes and checks the progress or quality of something over a period of time.",
  "A reverse proxy sits in front of web servers and forwards client requests to those servers.",
  "Environment variables are dynamic named values that can affect the way running processes behave on a computer.",
  "SSH provides a secure channel over an unsecured network using a client-server architecture.",
  "API gateways act as a single entry point for a defined group of microservices.",
  "Version control systems track and provide control over changes to source code.",

  // Algorithms / Data Structures
  "Binary search trees maintain their keys in sorted order so that lookup and other operations can use binary search.",
  "Hash tables implement an associative array that maps keys to values using a hash function.",
  "Linked lists are linear collections of data elements whose order is not given by their physical placement in memory.",
  "Stacks follow the Last In First Out principle where the last element added is the first one to be removed.",
  "Queues follow the First In First Out principle where the first element added is the first one to be removed.",
  "Graphs consist of vertices connected by edges and can represent networks of communication or data organization.",
  "Depth-first search explores as far as possible along each branch before backtracking.",
  "Breadth-first search explores all neighbor nodes at the present depth before moving to nodes at the next depth level.",
  "Dynamic programming solves complex problems by breaking them down into simpler subproblems and storing their solutions.",
  "Greedy algorithms make locally optimal choices at each stage with the hope of finding a global optimum.",
  "Merge sort divides an array into two halves, recursively sorts them, and then merges the sorted halves.",
  "Quick sort selects a pivot element and partitions the array around it, then recursively sorts the partitions.",
  "Heaps are specialized tree-based data structures that satisfy the heap property.",
  "Tries are tree-like data structures that store a dynamic set of strings for efficient retrieval.",
  "Dijkstra's algorithm finds the shortest path between nodes in a graph with non-negative edge weights.",

  // Testing / Quality
  "Unit tests verify that individual components of the software perform as designed.",
  "Integration tests verify that different modules or services work well together.",
  "End-to-end testing validates the flow of an application from start to finish.",
  "Test-driven development writes tests before writing the code that needs to be tested.",
  "Code coverage measures the percentage of code executed during automated tests.",
  "Mocking replaces real objects with simulated ones that mimic the behavior of real objects in controlled ways.",
  "Regression testing ensures that previously developed and tested software still performs after a change.",
  "Load testing simulates real-world load on any software, application, or website.",
  "Static code analysis examines code without executing it to find potential errors and security vulnerabilities.",
  "Linters analyze source code to flag programming errors, bugs, stylistic errors, and suspicious constructs.",

  // Security
  "Cross-site scripting allows attackers to inject malicious scripts into web pages viewed by other users.",
  "CORS is a mechanism that allows restricted resources on a web page to be requested from another domain.",
  "HTTPS encrypts data sent between a browser and a web server using SSL or TLS protocols.",
  "Salting adds random data to passwords before hashing to protect against rainbow table attacks.",
  "OAuth is an open standard for access delegation commonly used for token-based authentication.",
  "Principle of least privilege means giving users the minimum levels of access needed to perform their job functions.",
  "Input validation ensures that only properly formed data enters the workflow in an information system.",
  "Content Security Policy helps detect and mitigate certain types of attacks including XSS and data injection.",
  "SQL prepared statements separate SQL logic from data to prevent injection attacks.",

  // Code Quality & Patterns
  "The factory pattern creates objects without specifying the exact class of object that will be created.",
  "The singleton pattern ensures a class has only one instance and provides a global point of access to it.",
  "The observer pattern defines a one-to-many dependency between objects so that when one object changes state, all dependents are notified.",
  "The decorator pattern attaches additional responsibilities to an object dynamically without modifying its structure.",
  "The strategy pattern defines a family of algorithms and makes them interchangeable within that family.",
  "Code smells are surface indicators that usually correspond to deeper problems in the system.",
  "Refactoring improves the internal structure of code without changing its external behavior.",
  "Technical debt refers to the implied cost of additional rework caused by choosing an easy solution now instead of a better approach.",
  "DRY principle stands for Don't Repeat Yourself and emphasizes reducing repetition in code.",
  "KISS principle means Keep It Simple, Stupid and advocates for simplicity in design.",
  "YAGNI stands for You Aren't Gonna Need It and advises against adding functionality until it is necessary.",
  "The adapter pattern converts the interface of a class into another interface that clients expect.",
  "The facade pattern provides a simplified interface to a complex subsystem.",
  "The command pattern encapsulates a request as an object, thereby allowing parameterization of clients with different requests.",
  "The builder pattern separates the construction of a complex object from its representation.",

  // Async & Concurrency
  "Promises represent the eventual completion or failure of an asynchronous operation and its resulting value.",
  "Async/await syntax makes asynchronous code look and behave more like synchronous code.",
  "Callbacks are functions passed as arguments to other functions to be executed after some operation completes.",
  "Race conditions occur when the behavior of software depends on the relative timing of events.",
  "Deadlocks happen when two or more processes are unable to proceed because each is waiting for the other to release a resource.",
  "Thread pools maintain multiple threads waiting for tasks to be allocated for concurrent execution.",
  "Event loops handle asynchronous callbacks in JavaScript by continuously checking the message queue.",
  "Mutex locks ensure that only one thread can access a shared resource at a time.",
  "Semaphores control access to a common resource by multiple processes in a concurrent system.",
  "Debouncing delays the processing of a function until after a certain amount of time has passed since its last invocation.",
  "Throttling ensures a function is called at most once in a specified time period.",
  "Web Workers run scripts in background threads separate from the main execution thread.",
  "Generators are functions that can be exited and later re-entered with their context saved across re-entrances.",
  "Streams process data piece by piece without loading the entire content into memory.",
  "Microtasks are executed before the next rendering and before any other tasks in the event loop.",

  // Modern JavaScript/TypeScript
  "Destructuring assignment unpacks values from arrays or properties from objects into distinct variables.",
  "Spread operators allow an iterable to be expanded in places where zero or more arguments or elements are expected.",
  "Template literals allow embedded expressions and multi-line strings using backtick characters.",
  "Arrow functions provide a more concise syntax for writing function expressions and lexically bind the this value.",
  "Default parameters allow named parameters to be initialized with default values if no value is passed.",
  "Rest parameters represent an indefinite number of arguments as an array.",
  "Optional chaining allows reading the value of a property deep within a chain of connected objects without checking each reference.",
  "Nullish coalescing returns the right operand when the left operand is null or undefined.",
  "Modules encapsulate code and provide explicit imports and exports for managing dependencies.",
  "Type guards narrow down the type of a variable within a conditional block in TypeScript.",
  "Generics enable writing reusable code components that work with multiple types rather than a single one.",
  "Interfaces define contracts in TypeScript that classes or objects must adhere to.",
  "Enums allow defining a set of named constants in TypeScript.",
  "Union types allow a variable to be one of several types.",
  "Type assertions tell the TypeScript compiler to treat a value as a specific type.",

  // Performance & Optimization
  "Lazy loading defers initialization of resources until they are actually needed.",
  "Code splitting breaks up application bundles into smaller chunks that can be loaded on demand.",
  "Tree shaking eliminates dead code from JavaScript bundles during the build process.",
  "Minification removes unnecessary characters from code without changing its functionality.",
  "Gzip compression reduces the size of HTTP responses for faster transmission.",
  "CDNs distribute content across multiple geographically dispersed servers to reduce latency.",
  "Pagination divides large datasets into discrete pages to improve load times and user experience.",
  "Infinite scroll automatically loads content as the user scrolls down the page.",
  "Request batching combines multiple API requests into a single request to reduce overhead.",
  "Connection pooling maintains a cache of database connections to be reused for future requests.",
  "Prefetching loads resources before they are needed based on predicted user actions.",
  "Service workers act as proxy servers between web applications and the network for offline functionality.",
  "Image optimization reduces file size through compression and format selection without sacrificing quality.",
  "Critical rendering path is the sequence of steps browsers take to convert HTML, CSS, and JavaScript into pixels on screen.",
  "Reflows recalculate element positions and geometries when the DOM structure changes.",

  // Error Handling & Debugging
  "Try-catch blocks handle exceptions that occur during code execution gracefully.",
  "Error boundaries catch JavaScript errors in React component trees and display fallback UIs.",
  "Stack traces show the sequence of function calls that led to an error.",
  "Breakpoints pause code execution at specific lines to inspect variable values and program flow.",
  "Console logging outputs messages to the browser console for debugging purposes.",
  "Source maps map minified code back to the original source code for easier debugging.",
  "Graceful degradation ensures applications remain functional even when some features fail.",
  "Circuit breakers prevent cascading failures by stopping requests to failing services.",
  "Retry logic automatically attempts failed operations again after a delay.",
  "Error monitoring services track and aggregate errors in production applications.",

  // APIs & Communication
  "Webhooks allow applications to send real-time data to other applications when events occur.",
  "Pagination tokens provide a way to fetch large result sets in smaller chunks.",
  "API versioning manages changes to APIs while maintaining backward compatibility.",
  "SOAP is a protocol for exchanging structured information using XML in web services.",
  "RPC allows programs to execute procedures on remote servers as if they were local.",
  "Server-sent events enable servers to push updates to clients over HTTP.",
  "Long polling keeps HTTP connections open until the server has new data to send.",
  "Content negotiation selects the best representation for a response based on client capabilities.",
  "HATEOAS provides information dynamically through hypermedia in REST APIs.",
  "API rate limits restrict the number of requests a client can make within a time window.",

  // Functional Programming
  "Higher-order functions take other functions as arguments or return functions as results.",
  "Map transforms each element of an array by applying a function to it.",
  "Filter creates a new array with elements that pass a test implemented by a provided function.",
  "Reduce executes a reducer function on each element of an array, resulting in a single output value.",
  "Function composition combines multiple functions into a single function.",
  "Currying transforms a function with multiple arguments into a sequence of functions each taking a single argument.",
  "Partial application fixes a number of arguments to a function, producing another function of smaller arity.",
  "Side effects occur when a function modifies state outside its scope or has observable interactions besides returning a value.",
  "Referential transparency means a function call can be replaced with its resulting value without changing program behavior.",
  "Functors are objects that implement a map method following specific laws.",
];
