export const SENTENCES = [
  // General / Concepts
  "Clean code always looks like it was written by someone who cares.",
  "Premature optimization is the root of all evil in programming.",
  "Recursion is a method where the solution depends on solutions to smaller instances of the same problem.",
  "A closure is the combination of a function bundled together with references to its surrounding state.",
  "Big O notation is used to classify algorithms according to how their run time or space requirements grow.",
  "The single responsibility principle states that every module or class should have responsibility over a single part of the functionality.",
  "Dependency injection is a technique whereby one object supplies the dependencies of another object.",
  "Polymorphism allows objects of different types to be accessed through the same interface.",
  "Encapsulation is the bundling of data with the methods that operate on that data.",

  // Frontend
  "React components implement a render method that takes input data and returns what to display.",
  "CSS Grid Layout excels at dividing a page into major regions or defining the relationship in terms of size, position, and layer.",
  "The Document Object Model is a cross-platform and language-independent interface that treats an XML or HTML document as a tree structure.",
  "Event bubbling describes how the browser handles events targeted at nested elements.",
  "TypeScript adds static typing to JavaScript to enable better tooling and catch errors early.",
  "Virtual DOM is a programming concept where an ideal representation of a UI is kept in memory and synced with the real DOM.",
  "Flexbox is a one-dimensional layout method for arranging items in rows or columns.",
  "Shadow DOM provides encapsulation for the JavaScript, CSS, and templating in a Web Component.",
  "Server-side rendering generates the full HTML for a page on the server in response to navigation.",
  "Web Components are a suite of different technologies allowing you to create reusable custom elements.",
  "The useState hook lets you add React state to function components.",
  "useEffect performs side effects in function components and serves the same purpose as lifecycle methods.",

  // Backend / Database
  "RESTful APIs use standard HTTP methods like GET, POST, PUT, and DELETE to perform operations on resources.",
  "SQL injection is a code injection technique that might destroy your database.",
  "Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity.",
  "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
  "ACID properties ensure that database transactions are processed reliably.",
  "Middleware functions have access to the request object, response object, and the next middleware function in the cycle.",
  "GraphQL is a query language for APIs that provides a complete description of the data in your API.",
  "MongoDB is a document-oriented NoSQL database used for high volume data storage.",
  "An ORM is a technique that lets you query and manipulate data from a database using an object-oriented paradigm.",
  "JWT tokens contain three parts separated by dots: header, payload, and signature.",
  "Microservices architecture structures an application as a collection of loosely coupled services.",
  "Load balancing distributes network traffic across multiple servers to ensure no single server bears too much demand.",

  // DevOps / Tools
  "Git is a distributed version control system for tracking changes in source code during software development.",
  "Docker containers wrap up a piece of software in a complete filesystem that contains everything it needs to run.",
  "Continuous Integration is the practice of merging all developers' working copies to a shared mainline several times a day.",
  "Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications.",
  "CI/CD pipelines automate the steps in your software delivery process such as builds, tests, and deployments.",
  "Infrastructure as code manages and provisions computing infrastructure through machine-readable definition files.",
  "Blue-green deployment is a technique that reduces downtime by running two identical production environments.",
  "Feature flags allow you to turn features on and off without deploying new code.",

  // Algorithms / Data Structures
  "Binary search trees maintain their keys in sorted order so that lookup and other operations can use binary search.",
  "Hash tables implement an associative array that maps keys to values using a hash function.",
  "Linked lists are linear collections of data elements whose order is not given by their physical placement in memory.",
  "Stacks follow the Last In First Out principle where the last element added is the first one to be removed.",
  "Queues follow the First In First Out principle where the first element added is the first one to be removed.",
  "Graphs consist of vertices connected by edges and can represent networks of communication or data organization.",
  "Depth-first search explores as far as possible along each branch before backtracking.",

  // Testing / Quality
  "Unit tests verify that individual components of the software perform as designed.",
  "Integration tests verify that different modules or services work well together.",
  "End-to-end testing validates the flow of an application from start to finish.",
  "Test-driven development writes tests before writing the code that needs to be tested.",
  "Code coverage measures the percentage of code executed during automated tests.",

  // Security
  "Cross-site scripting allows attackers to inject malicious scripts into web pages viewed by other users.",
  "CORS is a mechanism that allows restricted resources on a web page to be requested from another domain.",
  "HTTPS encrypts data sent between a browser and a web server using SSL or TLS protocols.",

  // Code Quality & Patterns
  "The factory pattern creates objects without specifying the exact class of object that will be created.",
  "The singleton pattern ensures a class has only one instance and provides a global point of access to it.",
  "The observer pattern defines a one-to-many dependency between objects so that when one object changes state, all dependents are notified.",
  "The decorator pattern attaches additional responsibilities to an object dynamically without modifying its structure.",
  "The strategy pattern defines a family of algorithms and makes them interchangeable within that family.",
  "Code smells are surface indicators that usually correspond to deeper problems in the system.",

  // Async & Concurrency
  "Promises represent the eventual completion or failure of an asynchronous operation and its resulting value.",
  "Async/await syntax makes asynchronous code look and behave more like synchronous code.",
  "Callbacks are functions passed as arguments to other functions to be executed after some operation completes.",
  "Race conditions occur when the behavior of software depends on the relative timing of events.",
  "Deadlocks happen when two or more processes are unable to proceed because each is waiting for the other to release a resource.",
  "Thread pools maintain multiple threads waiting for tasks to be allocated for concurrent execution.",

  // Modern JavaScript/TypeScript
  "Destructuring assignment unpacks values from arrays or properties from objects into distinct variables.",
  "Spread operators allow an iterable to be expanded in places where zero or more arguments or elements are expected.",
  "Template literals allow embedded expressions and multi-line strings using backtick characters.",
  "Arrow functions provide a more concise syntax for writing function expressions and lexically bind the this value.",
  "Default parameters allow named parameters to be initialized with default values if no value is passed.",

  // Performance & Optimization
  "Lazy loading defers initialization of resources until they are actually needed.",
  "Code splitting breaks up application bundles into smaller chunks that can be loaded on demand.",
  "Tree shaking eliminates dead code from JavaScript bundles during the build process.",
  "Minification removes unnecessary characters from code without changing its functionality.",
  "Gzip compression reduces the size of HTTP responses for faster transmission.",

  // Error Handling & Debugging
  "Try-catch blocks handle exceptions that occur during code execution gracefully.",
  "Error boundaries catch JavaScript errors in React component trees and display fallback UIs.",
  "Stack traces show the sequence of function calls that led to an error.",
  "Breakpoints pause code execution at specific lines to inspect variable values and program flow.",
  "Console logging outputs messages to the browser console for debugging purposes.",

  // APIs & Communication
  "Webhooks allow applications to send real-time data to other applications when events occur.",
  "Pagination tokens provide a way to fetch large result sets in smaller chunks.",
  "API versioning manages changes to APIs while maintaining backward compatibility.",
  "SOAP is a protocol for exchanging structured information using XML in web services.",
  "RPC allows programs to execute procedures on remote servers as if they were local.",

  // Functional Programming
  "Higher-order functions take other functions as arguments or return functions as results.",
  "Map transforms each element of an array by applying a function to it.",
  "Filter creates a new array with elements that pass a test implemented by a provided function.",
  "Reduce executes a reducer function on each element of an array, resulting in a single output value.",
  "Function composition combines multiple functions into a single function.",

  "Immutability means that once a data structure is created, it cannot be changed, requiring new copies for modifications.",
  "Hoisting is JavaScript's default behavior of moving declarations to the top of the current scope before code execution.",
  "The event loop handles asynchronous callbacks by processing the call stack and task queue in a continuous cycle.",
  "Debouncing delays function execution until after a specified time has passed since it was last invoked.",
  "Throttling ensures a function is called at most once in a specified time period regardless of how many times it's triggered.",
  "A data structure is a specialized format for organizing, processing, retrieving and storing data efficiently.",
  "The principle of least privilege states that code should only have access to the resources necessary to perform its function.",
  "Idempotence means that making multiple identical requests has the same effect as making a single request.",
  "A pure function returns the same output for the same input and has no side effects on external state.",
  "Separation of concerns divides a program into distinct sections where each section addresses a separate concern.",
  "Lexical scoping means that the scope of a variable is defined by its location within the source code.",
  "The repository pattern mediates between the domain and data mapping layers using a collection-like interface.",
  "Cache invalidation determines when to remove stale data from a cache to ensure consistency with the source.",
  "Eventual consistency guarantees that if no new updates are made, all replicas will eventually return the same value.",
  "Two-phase commit is a protocol that ensures all participants in a distributed transaction agree to commit or rollback.",
  "Sharding partitions data across multiple databases to improve performance and distribute load horizontally.",
  "Indexing improves database query performance by creating data structures that allow fast retrieval of records.",
  "The adapter pattern converts the interface of a class into another interface that clients expect to work with.",
  "Garbage collection automatically frees memory by removing objects that are no longer referenced by the program.",
  "The call stack tracks active subroutines and manages function execution order in a last-in-first-out manner.",
  "Currying transforms a function with multiple arguments into a sequence of functions each taking a single argument.",
  "A binary heap is a complete binary tree where each node is greater than or equal to its children in a max heap.",
  "Tail recursion occurs when a recursive call is the last operation in a function, allowing stack optimization by the compiler.",
  "The facade pattern provides a simplified interface to a complex subsystem of classes, libraries, or frameworks.",
  "Dynamic programming solves complex problems by breaking them down into simpler overlapping subproblems and storing their results to avoid recomputation.",
  "Greedy algorithms make locally optimal choices at each step with the hope of finding a global optimum solution.",
  "Divide and conquer breaks a problem into smaller subproblems, solves them independently, then combines their solutions.",
  "Breadth-first search explores all vertices at the present depth before moving to vertices at the next depth level.",
  "Topological sorting orders directed acyclic graph vertices such that for every directed edge, the source vertex comes before the destination vertex.",
  "Red-black trees are self-balancing binary search trees that maintain balance through color properties and tree rotations.",
  "Tries are tree-like data structures used to store associative arrays where keys are usually strings, enabling efficient prefix searches.",
  "Bloom filters are space-efficient probabilistic data structures used to test whether an element is in a set, with possible false positives but no false negatives.",
  "The command pattern encapsulates a request as an object, thereby allowing parameterization of clients with different requests and queuing of requests.",
  "SOLID principles are five design principles intended to make object-oriented designs more understandable, flexible, and maintainable over time.",
  "Composition over inheritance favors building complex objects by combining simpler ones rather than inheriting behavior from parent classes.",
  "The Law of Demeter states that an object should only communicate with its immediate neighbors and not with strangers in the object graph.",
  "YAGNI principle advises developers not to add functionality until it is actually necessary to avoid unnecessary complexity.",
  "DRY principle states that every piece of knowledge or logic must have a single, unambiguous, authoritative representation within a system.",
  "Inversion of control transfers the control of objects or portions of a program to a container or framework instead of custom code.",
  "Service workers are scripts that run in the background separate from web pages and enable features like offline functionality and push notifications.",
  "WebSockets provide full-duplex communication channels over a single TCP connection for real-time bidirectional data transfer between client and server.",
  "Local storage provides a way to store key-value pairs in a web browser with no expiration date across browser sessions.",
  "Session storage maintains a separate storage area for each origin that's available only for the duration of the page session.",
  "IndexedDB is a low-level API for client-side storage of significant amounts of structured data including files and blobs using indexes.",
  "Progressive web apps use modern web capabilities to deliver app-like experiences to users with offline support and installability.",
  "Service mesh provides infrastructure layer for service-to-service communication with features like load balancing, service discovery, and monitoring.",
  "Circuit breakers prevent cascading failures in distributed systems by stopping requests to a service that is experiencing failures or high latency.",
  "Saga pattern manages distributed transactions by coordinating a sequence of local transactions across multiple services with compensating transactions for rollback.",
  "Event sourcing stores all changes to application state as a sequence of events rather than storing just the current state, enabling time travel and audit logs.",
  "CQRS separates read and write operations for a data store to optimize performance, scalability, and security independently for queries and commands.",
  "Message queues enable asynchronous communication between distributed services by storing messages until they can be processed by consumers.",
  "Pub-sub pattern decouples message senders from receivers using an event bus or message broker that routes messages based on topics or content.",
  "Rate limiting controls the number of requests a client can make to an API within a specified time window to prevent abuse and ensure fair usage.",
  "API gateways provide a single entry point for clients to access multiple backend services while handling cross-cutting concerns like authentication and rate limiting.",
  "Reverse proxies sit between clients and backend servers, forwarding client requests and potentially caching responses to improve performance.",
  "Content delivery networks distribute static content across geographically dispersed servers to reduce latency and improve load times for users.",
  "Horizontal scaling adds more machines to a resource pool to handle increased load, while vertical scaling increases the resources of existing machines.",
  "The twelve-factor app methodology provides best practices for building modern, scalable, maintainable web applications suitable for deployment on cloud platforms.",
  "Semantic versioning uses a three-part version number major.minor.patch to communicate the nature and impact of changes between software releases.",
  "Mutation testing evaluates the quality of a test suite by introducing small changes to the code and checking if the tests catch these mutations.",
  "Property-based testing generates random test cases based on properties that should always hold true rather than writing individual test cases manually.",
  "Snapshot testing captures the rendered output of components and compares future outputs against the snapshot to detect unexpected changes in behavior.",
  "Mocking replaces real objects with test objects that simulate the behavior of real dependencies, allowing isolated testing of components.",
  "Stubbing provides predefined responses to function calls made during tests without executing the actual implementation of the stubbed functions.",
  "Static analysis examines source code without executing it to find bugs, code smells, security vulnerabilities, and style violations automatically.",
  "Linting analyzes code to flag programming errors, bugs, stylistic errors, and suspicious constructs based on configurable rules and best practices.",
  "Fuzz testing provides invalid, unexpected, or random data as input to programs to discover security vulnerabilities, crashes, and memory leaks.",
  "Regression testing ensures that recent code changes haven't adversely affected existing functionality by re-running previously passing tests.",
  "Canary deployments release new versions to a small subset of users before rolling out to the entire infrastructure to minimize risk of failures.",
  "Chaos engineering intentionally injects failures into production systems to test their resilience and ability to recover from unexpected conditions.",
  "Observability measures how well the internal states of a system can be inferred from its external outputs including logs, metrics, and traces.",
  "Distributed tracing tracks requests as they propagate through distributed microservices architectures to identify performance bottlenecks and failures.",
  "Time complexity measures how the runtime of an algorithm grows as a function of the input size using Big O notation.",
  "Space complexity measures how the memory usage of an algorithm grows as a function of the input size, including both auxiliary and input space.",
  "Amortized analysis considers the average performance of each operation in a sequence rather than analyzing worst-case performance of individual operations.",
  "The master theorem provides a cookbook solution for recurrence relations of the form T(n) = aT(n/b) + f(n) that arise in divide-and-conquer algorithms.",
  "Consistent hashing distributes keys across multiple nodes in a way that minimizes reorganization when nodes are added or removed from the cluster.",
  "Vector clocks provide a mechanism for capturing causality relationships between events in distributed systems without requiring synchronized clocks.",
  "CAP theorem states that distributed systems can provide at most two of consistency, availability, and partition tolerance simultaneously.",
  "BASE model provides an alternative to ACID by favoring availability through basically available, soft state, and eventual consistency properties.",
  "Merkle trees are hash trees where each non-leaf node is labeled with the hash of its children, enabling efficient verification of large data structures.",
  "Conflict-free replicated data types are data structures that can be replicated across multiple nodes and updated independently without coordination.",
  "Gossip protocols spread information through a network by having nodes periodically exchange state with random peers, achieving eventual consistency.",
  "Byzantine fault tolerance enables distributed systems to reach consensus even when some nodes fail or act maliciously by requiring agreement from a supermajority.",
  "Paxos is a consensus algorithm that ensures a group of distributed processes can agree on a single value despite failures and message delays.",
  "Raft is a consensus algorithm designed to be more understandable than Paxos while providing equivalent fault tolerance and performance guarantees.",
];
